services:
  next:
    build: 
      context: .
      target: next
    ports:
      - "3000:3000"
    environment:
        - NODE_ENV=development
        - PORT=3000
    command: ["npm", "run", "dev"]
    volumes:
        - .:/app